### ISSUE TITLE
vite proxy not working correctly on windows with node 22 

### ISSUE THREAD

**Issue by pagoru** [openhotel/openhotel#469]

**Comment by serNAVARRO7** [comment]
To avoid this problem, I ran the project using WSL with the following setup:

Debian
- Node: 18.19.0
- Deno: 2.1.4
- Yarn: 1.22.22

I discovered that changing the Vite config URLs from http://localhost:19940 to http://127.0.0.1:19940 fixed the issue on my Windows machine. Why?

> Starting with Node 17, localhost resolution prefers IPv6 addresses (::1) over IPv4 (127.0.0.1).

When Vite tried to connect to http://localhost:19940, it resolved to ::1 which caused the ECONNREFUSED error because the server was not listening on that IPv6 address.

> On most systems, when a server listens on the unspecified IPv6 address (::), it also listens on the unspecified IPv4 address (0.0.0.0). 

However, Windows behaves differently in this regard and Deno doesn't seem to provide a [solution](https://github.com/denoland/deno/issues/10762) for this specific case.
